version: '3.8'

services:
  xteve:
    image: dnsforge/xteve:latest # Or another suitable image like alturismo/xteve
    container_name: xteve
    network_mode: host # Recommended for easier network access and HDHomeRun emulation
    # Or use bridge mode with port mapping:
    # ports:
    #   - "34400:34400" # xTeVe web UI
    #   - "5004:5004" # HDHomeRun emulation port (if needed)
    environment:
      - PUID=1000 # User ID (adjust as needed)
      - PGID=1000 # Group ID (adjust as needed)
      - TZ=Europe/Berlin # Set your timezone
    volumes:
      - /path/to/your/xteve/config:/xteve/config # Persistent storage for xTeVe configuration
      - /path/to/your/xteve/data:/xteve/data # Persistent storage for data (e.g., EPG, channel logos)
    restart: unless-stopped
