version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: emby_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: 'false'
    container_name: emby_app_proxy_1
  server:
    image: >-
      linuxserver/emby:4.8.11@sha256:3e9b2363fe16c3858fe8c7e32e949d819f85cb3be6705ceb37977e9c7b618e82
    environment:
      TZ: Europe/Berlin
      UID: 1000
      GID: 1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${UMBREL_ROOT}/home/Downloads:/downloads
      - ${UMBREL_ROOT}/home/Videos:/mnt/emby/symlinks
      - /home/username/docker/DMB/mnt/debrid:/mnt/debrid
    container_name: emby_server_1

    depends_on:                                             ## Used to delay the startup of plex to ensure the rclone mount is available.
      DMB:                                                  ## The name of the container running rclone
        condition: service_healthy
        restart: true                                       ## Will automatically restart the plex container if the DMB container restarts
