version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: emby_server_1
      APP_PORT: 8096
      PROXY_AUTH_ADD: 'false'
    container_name: emby_app_proxy_1
  server:
    image: >-
      linuxserver/emby:4.8.11@sha256:3e9b2363fe16c3858fe8c7e32e949d819f85cb3be6705ceb37977e9c7b618e82
    environment:
      TZ: Europe/Berlin
      UID: 0
      GID: 0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${UMBREL_ROOT}/home/Downloads:/downloads
      - /home/username/docker/DMB/mnt/debrid/riven_symlinks:/mnt/symlinks
      - /home/username/docker/DMB/mnt/debrid/riven/movies:/mnt/movies
      - /home/username/docker/DMB/mnt/debrid/riven/shows:/mnt/shows
    container_name: emby_server_1
