version: '3'
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      # Set the timezone to your local timezone
      - TZ=America/New_York
    ports:
      - '8945:8945'
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/home/Videos/yt:/mnt/yt
      - ${UMBREL_ROOT}/home/Music/mp3:/mnt/mp3
      - ${UMBREL_ROOT}/home/Music/videos:/mnt/videos
      - ${UMBREL_ROOT}/home/downloads:/downloads