name: spotify-downloader

services:
  spotify-downloader:
    image: pjmeca/spotify-downloader:latest
    build: ./SpotifyDownloader
    container_name: spotify-downloader
    restart: unless-stopped
    volumes:
      - ${UMBREL_ROOT}/home/Music:/misic
      - ./app:/app
      - ./tracking.yaml:/app/tracking.yaml:ro
    environment:
      TZ: Europe/Madrid
      CRON_SCHEDULE: "0 0 * * *"
      CLIENT__ID: a51715db21f14a64a38293da0ade398f
      CLIENT__SECRET: 3a62bb82cff74c41b7f531e911542f4c
      FORMAT: "opus" # Music format. Must be compatible with spotdl. Defaults to "opus".
      OPTIONS: "" # Additional spotdl options.