version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: brcly-playit_server_1
      APP_PORT: 8585
      PROXY_AUTH_ADD: "false"
  
  server:
    image: wisdomsky/playit-docker-web:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config


16f3cf3db801b3acef12aa934007c997a0cb913e96faf758028af7d16412fffe

docker run --rm --net=host -e SECRET_KEY=16f3cf3db801b3acef12aa934007c997a0cb913e96faf758028af7d16412fffe playitcloud/playit:0.15.19

