{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # Zurg configuration version\
zurg: v1\
token: ENTER REAL-DEBRID API TOKEN HERE # https://real-debrid.com/apitoken\
# host: "[::]"\
# port: 9999\
# username:\
# password:\
# proxy:\
api_rate_limit_per_minute: 60\
torrents_rate_limit_per_minute: 25\
concurrent_workers: 32\
check_for_changes_every_secs: 10\
# repair_every_mins: 60\
ignore_renames: true\
retain_rd_torrent_name: true\
retain_folder_name_extension: true\
enable_repair: false\
auto_delete_rar_torrents: false\
get_torrents_count: 5000\
# api_timeout_secs: 15\
# download_timeout_secs: 10\
# enable_download_mount: false\
# rate_limit_sleep_secs: 6\
# retries_until_failed: 2\
# network_buffer_size: 4194304 # 4MB\
# serve_from_rclone: false\
# verify_download_link: false\
# force_ipv6: false}