services:
  cinesync:
    image: sureshfizzy/cinesync:feature
    container_name: cinesync
    restart: unless-stopped
    ports:
      - "5173:5173"  # Web Interface
      - "8082:8082"  # API & WebDAV
    environment:
      - PUID=1000    # Set to your user ID
      - PGID=1000    # Set to your group ID
      - TZ=UTC       # Set your timezone
      - SOURCE_DIR=/mnt/debrid/riven/__all__
      - DESTINATION_DIR=/videoes
      - CINESYNC_LAYOUT=true
      - ANIME_SEPARATION=true
      - KIDS_SEPARATION=true
      - CUSTOM_KIDS_MOVIE_FOLDER=Kids Movies
      - CUSTOM_KIDS_SHOW_FOLDER=Kids TV
      - TMDB_API_KEY=388d81cb7c76ecc839c37ff99ff57bfd
      - ANIME_SCAN=true
      - RENAME_ENABLED=true
      
      
    volumes:
      # Configuration and database
      - ./.env:/app/.env
      - ./db:/app/db
      - /home:/home
      - /mnt:/mnt
      - ${UMBREL_ROOT}/home/Videos:/videoes
      - /home/username/docker/DMB/mnt/debrid:/mnt/debrid
